---
# General vars
toolset_supported_families:
  - Debian

common_packages:
  - apt-transport-https
  - software-properties-common
  - gnupg2
  - curl
  - ca-certificates
  - wget

# Microsoft vars
ms_repo_key: https://packages.microsoft.com/keys/microsoft.asc

# Visual Studio Code vars
vscode_repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
vscode_packages:
  - code

# Virtualbox vars
virtualbox_repo_key: https://www.virtualbox.org/download/oracle_vbox_2016.asc
virtualbox_repo: "deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release if ansible_distribution_release not in ['impish','focal'] else 'eoan' }} contrib"
virtualbox_branch: 6.1
virtualbox_packages:
  - "virtualbox-{{ virtualbox_branch }}"

# HashiCorp repository, courtesy of HashiCorp
hashicorp_repo_key_url: https://apt.releases.hashicorp.com/gpg
vagrant_old_repo: deb https://vagrant-deb.linestarve.com/ any main
hashicorp_repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
hashicorp_packages:
  - vagrant
  - terraform

# Entertainment
spotify_gpg_key: https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg
spotify_repo: "deb http://repository.spotify.com stable non-free"
entertainment_packages:
  - audacious
  - armagetronad
  - spotify-client

# Ansible's official repo
ansible_repo_key: 93C4A3FD7BB9C367
ansible_supported_dists:
  - artful
  - bionic
  - cosmic
  - disco
  - eoan
  - lucid
  - precise
  - saucy
  - trusty
  - utopic
  - vivid
  - wily
  - xenial
  - yakkety
  - zesty

ansible_branch_to_choose: "{{ 'trusty' if ansible_distribution_release not in ansible_supported_dists else ansible_distribution_release }}"
ansible_repo: "deb http://ppa.launchpad.net/ansible/ansible/ubuntu {{ ansible_branch_to_choose }} main"
ansible_packages:
  Debian:
    - python3-pip
    - python-pip
    - ansible
  Ubuntu:
    - ansible
    - python3-pip
    - python3-google-auth

ansible_pip_modules:
  Debian:
    - google-auth
  Ubuntu: []

# Docker CE repository
docker_key_url: https://download.docker.com/linux/ubuntu/gpg
docker_key_id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
docker_repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release if ansible_distribution_release != 'focal' else 'eoan' }} stable"
docker_packages:
  - docker-ce
docker_compose_version: 1.25.5
docker_compose_path: /usr/local/bin/docker-compose

# Cloud management software
cloud_packages:
  Debian:
    - python3-pip
    - awscli
  Ubuntu:
    - python3-pip
    - awscli

cloud_pip_modules:
  Debian:
    - SoftLayer
    - molecule
    - docker-py
  Ubuntu:
    - SoftLayer
    - molecule
    - docker-py

# Skype
skype_key_url: https://repo.skype.com/data/SKYPE-GPG-KEY
skype_repo: deb [arch=amd64] https://repo.skype.com/deb stable main
skype_packages:
  - skypeforlinux

# Zoom
zoom_deps:
  focal:
    - libglib2.0-0
    - libgstreamer-plugins-base1.0-0
    - libxcb-shape0
    - libxcb-shm0
    - libxcb-xfixes0
    - libxcb-randr0
    - libxcb-image0
    - libfontconfig1
    - libgl1-mesa-glx
    - libxi6
    - libsm6
    - libxrender1
    - libpulse0
    - libxcomposite1
    - libxslt1.1
    - libsqlite3-0
    - libxcb-keysyms1
    - libxcb-xtest0
    - ibus
  impish:
    - libglib2.0-0
    - libgstreamer-plugins-base1.0-0
    - libxcb-shape0
    - libxcb-shm0
    - libxcb-xfixes0
    - libxcb-randr0
    - libxcb-image0
    - libfontconfig1
    - libgl1-mesa-glx
    - libxi6
    - libsm6
    - libxrender1
    - libpulse0
    - libxcomposite1
    - libxslt1.1
    - libsqlite3-0
    - libxcb-keysyms1
    - libxcb-xtest0
    - ibus
zoom_package: https://zoom.us/client/latest/zoom_amd64.deb

# Slack
slack_repo_key: https://packagecloud.io/slacktechnologies/slack/gpgkey
slack_repo: "deb https://packagecloud.io/slacktechnologies/slack/debian/ jessie main"
slack_packages:
  - slack-desktop

# Network tools
network_packages:
  Debian:
    - iptraf-ng
    - network-manager-openvpn
    - network-manager-pptp
    - network-manager-openconnect
    - network-manager-ssh
    - network-manager-strongswan
    - network-manager-vpnc
    - rsync
    - rclone
  Ubuntu:
    - iptraf-ng
    - network-manager-openvpn
    - network-manager-openvpn-gnome
    - network-manager-pptp
    - network-manager-pptp-gnome
    - network-manager-fortisslvpn
    - network-manager-fortisslvpn-gnome
    - network-manager-iodine
    - network-manager-iodine-gnome
    - network-manager-l2tp
    - network-manager-l2tp-gnome
    - network-manager-openconnect
    - network-manager-openconnect-gnome
    - network-manager-ssh
    - network-manager-ssh-gnome
    - network-manager-strongswan
    - network-manager-vpnc
    - network-manager-vpnc-gnome
    - rsync
    - rclone

# Miscellaneous software
misc_packages:
  - git
  - vim
  - sysstat
  - lsof
  - lvm2
  - shellcheck
  - yamllint

# Google Chrome vars
chrome_repo_key: https://dl.google.com/linux/linux_signing_key.pub
chrome_repo: "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main"
chrome_packages:
  - google-chrome-stable
