---
- name: ANSIBLE | Repository key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ ansible_repo_key }}"
  when: (ansible_distribution_release in ansible_supported_dists)

- name: ANSIBLE | Official PPA repository for older distros
  apt_repository:
    repo: "{{ ansible_repo }}"
    state: present
    filename: ansible
    update_cache: yes
  when: (ansible_distribution_release in ansible_supported_dists)

- name: ANSIBLE | Software packages
  package:
    name: "{{ ansible_packages[ansible_distribution] }}"
    state: latest

- name: ANSIBLE | Additional Python modules
  pip:
    name: "{{ ansible_pip_modules[ansible_distribution] }}"
  when: (ansible_pip_modules[ansible_distribution] | length > 0)
