---

- name: Run the playbook tasks on the local host
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - include_vars: 'varsdata.yml'
    - fail:
        msg: 'This OS family is not supported '
      when: (ansible_os_family not in toolset_supported_families)
    - name: 'Ensure https transport is in place'
      action: >
        {{ ansible_pkg_mgr }} name={{ common_packages }} update_cache=yes cache_valid_time=300
    - include: "{{ item }}"
      with_items:
        - 'vscode.yml'
        - 'virtualbox.yml'
        - 'vagrant.yml'
        - 'ansiblerepo.yml'
        - 'docker.yml'
        - 'skype.yml'
        - 'slack.yml'
        - 'misc.yml'
        - 'entertainment.yml'
