---

- name: Run the playbook tasks on the local host
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: 'Ensure https transport is in place'
      action: >
        {{ ansible_pkg_mgr }} name='apt-transport-https' update_cache=yes cache_valid_time=300
    - include: "{{ item }}"
      with_items:
        - 'vscode.yml'
        - 'vbox.yml'
        - 'vagrant.yml'
        - 'ansiblerepo.yml'
        - 'docker.yml'
        - 'skype.yml'
        - 'slack.yml'
        - 'misc.yml'
        - 'entertainment.yml'

