---
- name: HASHICORP | Remove Linestarve repository no longer works
  apt_repository:
    repo: "{{ vagrant_old_repo }}"
    state: absent
    filename: wolfgang42-vagrant

- name: HASHICORP | Official HashiCorp GPG key
  apt_key:
    url: "{{ hashicorp_repo_key_url }}"

- name: HASHICORP | HashiCorp repository
  apt_repository:
    repo: "{{ hashicorp_repo }}"
    state: present
    filename: hashicorp-vagrant
    update_cache: yes

- name: HASHICORP | Hashicorp packages
  package:
    name: "{{ hashicorp_packages }}"
    state: present
