---
- name: SKYPE | GPG key
  apt_key:
    url: "{{ skype_key_url }}"
    state: present

- name: SKYPE | Repository
  apt_repository:
    repo: "{{ skype_repo }}"
    state: present
    filename: skype-stable
    update_cache: yes

- name: SKYPE | Software packages
  package:
    name: "{{ skype_packages }}"
    state: present
