---
- name: SLACK | Check Slack installation
  shell: dpkg-query -l slack-desktop|grep ^ii
  changed_when: False
  failed_when: False
  register: slack_deb_check

- name: SLACK | Software package download
  get_url:
    url: "{{ slack_deb_url }}"
    dest: "{{ slack_download_path }}"
    mode: "0644"
  when: (slack_deb_check.rc == 1)

- name: SLACK | Client installation
  command: "gdebi --n {{ slack_download_path }}"
  when: (slack_deb_check.rc == 1)
