---
- name: SLACK | Packagecloud Slack GPG key
  apt_key:
    url: "{{ slack_repo_key }}"

- name: SLACK | Packagecloud Slack repository
  apt_repository:
    repo: "{{ slack_repo }}"
    state: present
    filename: slack
    update_cache: yes

- name: SLACK | Slack app
  package:
    name: "{{ slack_packages }}"
    state: present
